### ISSUE TITLE
Suggestion to add off-side rule for log labeling

### ISSUE THREAD

**Issue by mahi97** [RoboCup-SSL/technical-challenge-rules#1]
Since the field is getting larger and the number of robots is increasing, I believe it's a good idea to add the off-side rule to SSL.

> it's originally added to soccer due to make the game more interesting by letting the defensive player participate in offensive plans without risking too much and also attackers cannot pass the ball to the forward unless it is a trough pass.
>
>I believe for the same reasons adding this rule to SSL can make games more interesting. 

But one of the problems for applying this rule directly for the game is, it looks a little bit tricky to detect a true off-side foul, so I guess if we just add this as part of log labeling it's a good practice for teams to develop auto-refs and team code in future.

**Comment by rhololkeolke** [comment]
Thanks for the suggestion.

Currently off-sides isn't in the SSL rules, and we're not sure that it will be added in future years. We believe that the no attacker touching the ball in the defense area rule accomplishes the same goal as an off-sides rule.

Also, for the labeling TC, we don't want to overwhelm teams with too many things to label. Given there are already 4 label types and we've never tried this before, we don't want to add new label types to this year's TC.
